/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommandList: typeof import('./components/CommandList.vue')['default']
    Components: typeof import('./components/index.vue')['default']
    KeyBinding: typeof import('./components/KeyBinding.vue')['default']
    KeyHistory: typeof import('./components/KeyHistory.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
